/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Kelompok1.View;

import Kelompok1.Controller.RegisterDosen;
import Kelompok1.Controller.RegisterMahasiswa;
import Kelompok1.Model.Koneksi;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;


/**
 *
 * @author TaufikH
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        ButtonPanelMahasiswa = new javax.swing.JButton();
        ButtonPanelDosen = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ButtonPanelAdmin = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        LoginMahasiswa = new javax.swing.JPanel();
        LabelMahasiswa = new javax.swing.JLabel();
        LabelPassMahasiswa = new javax.swing.JLabel();
        ButtonLoginMahasiswa = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        PasswordFieldMahasiswa = new javax.swing.JPasswordField();
        UsernameFieldMahasiswa = new javax.swing.JTextField();
        ButtonRegisterMahasiswa = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        LoginDosen = new javax.swing.JPanel();
        LabelUserDosen = new javax.swing.JLabel();
        LabelPassDosen = new javax.swing.JLabel();
        UsernameFieldDosen = new javax.swing.JTextField();
        PasswordFieldDosen = new javax.swing.JPasswordField();
        ButtonLoginDosen = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        ButtonRegisterDosen = new javax.swing.JButton();
        LoginAdmin = new javax.swing.JPanel();
        LabelUsernameAdmin = new javax.swing.JLabel();
        LabelPasswordAdmin = new javax.swing.JLabel();
        FieldUsernameAdmin = new javax.swing.JTextField();
        FieldPasswordAdmin = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        ButtonLoginAdmin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 0, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ButtonPanelMahasiswa.setText("Mahasiswa");
        ButtonPanelMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPanelMahasiswaActionPerformed(evt);
            }
        });

        ButtonPanelDosen.setText("Dosen");
        ButtonPanelDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPanelDosenActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Quizzzz");

        ButtonPanelAdmin.setText("Admin");
        ButtonPanelAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPanelAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(ButtonPanelMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonPanelAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonPanelDosen, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonPanelMahasiswa)
                    .addComponent(ButtonPanelDosen)
                    .addComponent(ButtonPanelAdmin))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(204, 0, 51));
        jPanel4.setLayout(new java.awt.CardLayout());

        LoginMahasiswa.setBackground(new java.awt.Color(204, 204, 204));
        LoginMahasiswa.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        LoginMahasiswa.setForeground(new java.awt.Color(102, 102, 102));
        LoginMahasiswa.setToolTipText("");

        LabelMahasiswa.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        LabelMahasiswa.setText("Username :");

        LabelPassMahasiswa.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        LabelPassMahasiswa.setText("Password  :");

        ButtonLoginMahasiswa.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ButtonLoginMahasiswa.setText("LOGIN");
        ButtonLoginMahasiswa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonLoginMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLoginMahasiswaActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Jika, belum memilki akun?");

        UsernameFieldMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameFieldMahasiswaActionPerformed(evt);
            }
        });

        ButtonRegisterMahasiswa.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ButtonRegisterMahasiswa.setText("Register");
        ButtonRegisterMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRegisterMahasiswaActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout LoginMahasiswaLayout = new javax.swing.GroupLayout(LoginMahasiswa);
        LoginMahasiswa.setLayout(LoginMahasiswaLayout);
        LoginMahasiswaLayout.setHorizontalGroup(
            LoginMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginMahasiswaLayout.createSequentialGroup()
                .addGroup(LoginMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginMahasiswaLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(LoginMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(LoginMahasiswaLayout.createSequentialGroup()
                                .addGroup(LoginMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LabelPassMahasiswa)
                                    .addComponent(LabelMahasiswa))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(LoginMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(UsernameFieldMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PasswordFieldMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(LoginMahasiswaLayout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(ButtonLoginMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LoginMahasiswaLayout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(ButtonRegisterMahasiswa)))
                .addContainerGap(151, Short.MAX_VALUE))
        );
        LoginMahasiswaLayout.setVerticalGroup(
            LoginMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginMahasiswaLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(LoginMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsernameFieldMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelMahasiswa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(LoginMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordFieldMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelPassMahasiswa))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonLoginMahasiswa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonRegisterMahasiswa)
                .addContainerGap())
        );

        jPanel4.add(LoginMahasiswa, "card2");

        LoginDosen.setBackground(new java.awt.Color(204, 204, 204));
        LoginDosen.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        LabelUserDosen.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        LabelUserDosen.setText("Username  :");

        LabelPassDosen.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        LabelPassDosen.setText("Password   :");

        UsernameFieldDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameFieldDosenActionPerformed(evt);
            }
        });

        ButtonLoginDosen.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ButtonLoginDosen.setText("LOGIN");
        ButtonLoginDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLoginDosenActionPerformed(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Jika, Belum memiliki akun?");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        ButtonRegisterDosen.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ButtonRegisterDosen.setText("Register");
        ButtonRegisterDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRegisterDosenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LoginDosenLayout = new javax.swing.GroupLayout(LoginDosen);
        LoginDosen.setLayout(LoginDosenLayout);
        LoginDosenLayout.setHorizontalGroup(
            LoginDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginDosenLayout.createSequentialGroup()
                .addGroup(LoginDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginDosenLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(LoginDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(LoginDosenLayout.createSequentialGroup()
                                .addComponent(LabelUserDosen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(UsernameFieldDosen, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(LoginDosenLayout.createSequentialGroup()
                                .addComponent(LabelPassDosen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PasswordFieldDosen, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(LoginDosenLayout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(ButtonRegisterDosen))
                    .addGroup(LoginDosenLayout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(ButtonLoginDosen, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        LoginDosenLayout.setVerticalGroup(
            LoginDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginDosenLayout.createSequentialGroup()
                .addGroup(LoginDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginDosenLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(UsernameFieldDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginDosenLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LabelUserDosen)))
                .addGap(18, 18, 18)
                .addGroup(LoginDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelPassDosen)
                    .addComponent(PasswordFieldDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(ButtonLoginDosen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonRegisterDosen)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(LoginDosen, "card3");

        LoginAdmin.setBackground(new java.awt.Color(204, 204, 204));
        LoginAdmin.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        LabelUsernameAdmin.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        LabelUsernameAdmin.setText("Username :");

        LabelPasswordAdmin.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        LabelPasswordAdmin.setText("Password :");

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));

        ButtonLoginAdmin.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ButtonLoginAdmin.setText("LOGIN");

        javax.swing.GroupLayout LoginAdminLayout = new javax.swing.GroupLayout(LoginAdmin);
        LoginAdmin.setLayout(LoginAdminLayout);
        LoginAdminLayout.setHorizontalGroup(
            LoginAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginAdminLayout.createSequentialGroup()
                .addGroup(LoginAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginAdminLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(LoginAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(LoginAdminLayout.createSequentialGroup()
                                .addGroup(LoginAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LabelUsernameAdmin)
                                    .addComponent(LabelPasswordAdmin))
                                .addGap(18, 18, 18)
                                .addGroup(LoginAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(FieldUsernameAdmin)
                                    .addComponent(FieldPasswordAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)))))
                    .addGroup(LoginAdminLayout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(ButtonLoginAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        LoginAdminLayout.setVerticalGroup(
            LoginAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginAdminLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(LoginAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelUsernameAdmin)
                    .addComponent(FieldUsernameAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(LoginAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPasswordAdmin)
                    .addComponent(FieldPasswordAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ButtonLoginAdmin)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel4.add(LoginAdmin, "card4");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(222, 222, 222))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonRegisterMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRegisterMahasiswaActionPerformed
        // TODO add your handling code here:
        RegisterMahasiswa rg = new RegisterMahasiswa();
        rg.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ButtonRegisterMahasiswaActionPerformed

    private void UsernameFieldMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameFieldMahasiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameFieldMahasiswaActionPerformed

    private void ButtonLoginMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLoginMahasiswaActionPerformed
        // TODO add your handling code here:
        try{
            Connection c = Koneksi.getKoneksi();
            Statement s = c.createStatement();
            
            String sql = "SELECT * FROM loginmahasiswa WHERE Username='" + UsernameFieldMahasiswa.getText()
                    +"' and Password='"+ PasswordFieldMahasiswa.getText() + "'";
            ResultSet r = s.executeQuery(sql);
            
            if (r.next()){
                JOptionPane.showMessageDialog(null, "Login Successfully");
                DashboardMahasiswaGUI dm = new DashboardMahasiswaGUI();
                dm.setVisible(true);
                this.dispose(); //close the form
            }else{
                JOptionPane.showMessageDialog(null, "Wrong Username or Password");
                PasswordFieldMahasiswa.requestFocus();
            }
        }catch(SQLException e){
            System.out.println("error");
        }
        

    }//GEN-LAST:event_ButtonLoginMahasiswaActionPerformed

    private void ButtonPanelMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPanelMahasiswaActionPerformed
        // TODO add your handling code here:
        jPanel4.removeAll();
        jPanel4.repaint();
        jPanel4.revalidate();
        jPanel4.add(LoginMahasiswa);
        jPanel4.repaint();
        jPanel4.revalidate();
    }//GEN-LAST:event_ButtonPanelMahasiswaActionPerformed

    private void UsernameFieldDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameFieldDosenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameFieldDosenActionPerformed

    private void ButtonLoginDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLoginDosenActionPerformed
        // TODO add your handling code here:
        try{
            Connection c = Koneksi.getKoneksi();
            Statement s = c.createStatement();
            
            String sql = "SELECT * FROM logindosen WHERE Username='" + UsernameFieldDosen.getText()
                    +"' and Password='"+ PasswordFieldDosen.getText() + "'";
            ResultSet r = s.executeQuery(sql);
            
            if (r.next()){
                JOptionPane.showMessageDialog(null, "Login Successfully");
                DashboardDosenGUI ds = new DashboardDosenGUI();
                ds.setVisible(true);
                this.dispose(); //close the form
            }else{
                JOptionPane.showMessageDialog(null, "Wrong Username or Password");
                PasswordFieldDosen.requestFocus();
            }
        }catch(SQLException e){
            System.out.println("error");
        }
        
    }//GEN-LAST:event_ButtonLoginDosenActionPerformed

    private void ButtonRegisterDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRegisterDosenActionPerformed
        // TODO add your handling code here:
        RegisterDosen rd = new RegisterDosen();
        rd.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ButtonRegisterDosenActionPerformed

    private void ButtonPanelDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPanelDosenActionPerformed
        // TODO add your handling code here:
        jPanel4.removeAll();
        jPanel4.repaint();
        jPanel4.revalidate();
        jPanel4.add(LoginDosen);
        jPanel4.repaint();
        jPanel4.revalidate();
    }//GEN-LAST:event_ButtonPanelDosenActionPerformed

    private void ButtonPanelAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPanelAdminActionPerformed
        // TODO add your handling code here:
        jPanel4.removeAll();
        jPanel4.repaint();
        jPanel4.revalidate();
        jPanel4.add(LoginAdmin);
        jPanel4.repaint();
        jPanel4.revalidate();
    }//GEN-LAST:event_ButtonPanelAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonLoginAdmin;
    private javax.swing.JButton ButtonLoginDosen;
    private javax.swing.JButton ButtonLoginMahasiswa;
    private javax.swing.JButton ButtonPanelAdmin;
    private javax.swing.JButton ButtonPanelDosen;
    private javax.swing.JButton ButtonPanelMahasiswa;
    private javax.swing.JButton ButtonRegisterDosen;
    private javax.swing.JButton ButtonRegisterMahasiswa;
    private javax.swing.JPasswordField FieldPasswordAdmin;
    private javax.swing.JTextField FieldUsernameAdmin;
    private javax.swing.JLabel LabelMahasiswa;
    private javax.swing.JLabel LabelPassDosen;
    private javax.swing.JLabel LabelPassMahasiswa;
    private javax.swing.JLabel LabelPasswordAdmin;
    private javax.swing.JLabel LabelUserDosen;
    private javax.swing.JLabel LabelUsernameAdmin;
    private javax.swing.JPanel LoginAdmin;
    private javax.swing.JPanel LoginDosen;
    private javax.swing.JPanel LoginMahasiswa;
    private javax.swing.JPasswordField PasswordFieldDosen;
    private javax.swing.JPasswordField PasswordFieldMahasiswa;
    private javax.swing.JTextField UsernameFieldDosen;
    private javax.swing.JTextField UsernameFieldMahasiswa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
